import { getTableConfig } from 'drizzle-orm/pg-core'
import { Client } from 'pg'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import * as schema from '@/db/schema'
import { startTestDatabase, type TestDatabase } from '../helpers/database'

/**
 * STRUCTURAL GUARD — the TypeScript schema and the migrated database say the
 * same thing.
 *
 * Migrations are generated by drizzle-kit but read and edited by hand, and the
 * policies are written by hand outright. That is deliberate (CLAUDE.md §7), and
 * it is exactly how the two drift apart: a column added to a hand-written
 * migration and never declared in TypeScript is invisible to every query, and
 * the next `pnpm db:generate` proposes to create it a second time.
 *
 * That already happened once: `invitations.client_id` was added in the 0007
 * migration, where it had to be — it references `clients` — but not declared in
 * `tenancy.ts`. Nothing failed. This test is what fails now.
 *
 * It is generated from the schema, so a new table is covered the day it exists.
 */

function declaredTables(): Map<string, Set<string>> {
  const tables = new Map<string, Set<string>>()

  for (const value of Object.values(schema)) {
    // The module also exports enums, helpers and types; only tables have a config.
    if (typeof value !== 'object' || value === null) continue
    let config: ReturnType<typeof getTableConfig>
    try {
      config = getTableConfig(value as Parameters<typeof getTableConfig>[0])
    } catch {
      continue
    }
    tables.set(config.name, new Set(config.columns.map((column) => column.name)))
  }

  return tables
}

describe('schema drift', () => {
  let db: TestDatabase
  let admin: Client
  let actual: Map<string, Set<string>>

  beforeAll(async () => {
    db = await startTestDatabase()
    admin = new Client({ connectionString: db.adminUrl })
    await admin.connect()

    const { rows } = await admin.query<{ table_name: string; column_name: string }>(
      `SELECT table_name, column_name FROM information_schema.columns
        WHERE table_schema = 'public'`,
    )

    actual = new Map()
    for (const row of rows) {
      const columns = actual.get(row.table_name) ?? new Set<string>()
      columns.add(row.column_name)
      actual.set(row.table_name, columns)
    }
  }, 180_000)

  afterAll(async () => {
    await admin?.end()
    await db?.stop()
  })

  it('found both sides to compare', () => {
    expect(declaredTables().size).toBeGreaterThan(10)
    expect(actual.size).toBeGreaterThan(10)
  })

  it('every table declared in TypeScript exists in the migrated database', () => {
    const missing = [...declaredTables().keys()].filter((table) => !actual.has(table))
    expect(missing, 'Declared in src/db/schema but never migrated').toEqual([])
  })

  it('declared columns and migrated columns agree, table by table', () => {
    const problems = [...declaredTables()].flatMap(([table, declared]) =>
      compare(table, declared, actual.get(table)),
    )

    expect(problems, 'Declare the column in src/db/schema, or drop it').toEqual([])
  })
})

function compare(table: string, declared: Set<string>, live: Set<string> | undefined): string[] {
  if (!live) return []

  return [
    ...[...declared]
      .filter((column) => !live.has(column))
      .map((column) => `${table}.${column}: declared, not in the database`),
    ...[...live]
      .filter((column) => !declared.has(column))
      .map((column) => `${table}.${column}: in the database, not declared`),
  ]
}
